version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul_dev
    restart: always
    ports:
      - "8500:8500"
    networks:
      - ar5go_networks

  db:
    container_name: ar5go_mysql
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3309:3306"
    volumes:
      - ar5go_db:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=ar5go_user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=ar5go_db
      - MYSQL_ROOT_PASSWORD=12345678
    tty: true
    networks:
      - ar5go_networks

  redis:
    image: 'bitnami/redis:6.0.9'
    container_name: redis_dev
    restart: always
    ports:
      - "6390:6379"
    environment:
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=password123
    volumes:
      - ar5go_cache:/bitnami/redis/data:rw
    networks:
      - ar5go_networks

  ar5go:
    container_name: ar5go
    build:
      context: .
    ports:
      - "8080:8080"
    command: serve  # make `serve` into `seed` or `seed --truncate=true` if anyone want to run the seeder
    volumes:
      - ./:/project
    environment:
      - CONSUL_URL=consul_dev:8500
      - CONSUL_PATH=ar5go
    tty: true
    depends_on:
      - consul
      - db
      - redis
    networks:
      - ar5go_networks
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  ar5go_networks:
    name: ar5go_networks
    driver: bridge

volumes:
  ar5go_db:
    name: ar5godb-data
  ar5go_cache:
    name: ar5gocache-data
